version: "2"
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - godot
    - gosec
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - prealloc
    - predeclared
    - unconvert
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocognit:
      min-complexity: 20
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - errorlint
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
